title: Home | Davin Leonardo
description: C. G. Davin Leonardo is an amateur composer of Classical music and Sacred Music from Indonesia, focusing on choral composition.
baseurl: ""
url: "https://davinleonardo.me"

collections:
  composition:
    output: true
  arrangement:
    output: true
  free-composition:
    output: true
  free-arrangement:
    output: true
  blog:
    output: true
theme: jekyll-theme-minimal